basePath: /msapi/domain
host: localhost:3000
info:
  contact:
    email: ortelius-dev@googlegroups.com
    name: Ortelius Google Group
  description: |-
    RestAPI for the Domain Object
    ![Release](https://img.shields.io/github/v/release/ortelius/domain?sort=semver)
    ![license](https://img.shields.io/github/license/ortelius/domain)

    ![Build](https://img.shields.io/github/actions/workflow/status/ortelius/domain/build-push-chart.yml)
    [![MegaLinter](https://github.com/ortelius/domain/workflows/MegaLinter/badge.svg?branch=main)](https://github.com/ortelius/domain/actions?query=workflow%3AMegaLinter+branch%3Amain)
    ![CodeQL](https://github.com/ortelius/domain/workflows/CodeQL/badge.svg)
    [![OpenSSF-Scorecard](https://api.securityscorecards.dev/projects/github.com/ortelius/domain/badge)](https://api.securityscorecards.dev/projects/github.com/ortelius/domain)

    ![Discord](https://img.shields.io/discord/722468819091849316)
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Ortelius v11 Domain Microservice
  version: 11.0.0
paths:
  /msapi/domain:
    get:
      consumes:
        - "*/*"
      description: Get a list of domains for the user.
      produces:
        - application/json
      responses:
        "200":
          description: OK
      summary: Get a List of Domains
      tags:
        - domain
    post:
      consumes:
        - application/json
      description: Create a new Domain and persist it
      produces:
        - application/json
      responses:
        "200":
          description: OK
      summary: Create a Domain
      tags:
        - domain
  /msapi/domain/:key:
    get:
      consumes:
        - "*/*"
      description: Get a domain based on the _key or name.
      produces:
        - application/json
      responses:
        "200":
          description: OK
      summary: Get a Domain
      tags:
        - domain
swagger: "2.0"
